# full or compact
display_mode: full

# Set to false to disable ANSI color escapes (useful for tests or piping output)
colorize: true

# Your github username
gh_handle:

# Example:
# - --label general
searches:

search_limit: 20

# Example:
# - gitub_user: green
author_colors:
